.TH GIT-BACKUP 1 2019-08-20 "git-backup 1.0.0" "Git Manual"

.SH NAME

git-backup \- create a backup commit from uncommited changes


.SH SYNOPSIS

.B git\-backup
[\fIOPTION\fR]...


.SH DESCRIPTION

.B git\-backup
.I creates
a backup commit
.I from
uncommited changes
.I inside
a separate branch.


.SH OPTIONS

.TP
.BR \-r " " \fIREMOTE\fR
change to which remote to push the backup branch to;
default=origin

.TP
.BR \-c " " \fICHARS\fR
max chars for branch name.
Your remote / git might complain that the branch name
is too long. You can limit it's length here;
default=255

.TP
.BR \-l
local mode. Will NOT push the generated branch to remote;
default=false

.TP
.BR \-q
quite mode. Will only print the backup branches' name;
default=false

.TP
.BR \-h
display this \fIhelp\fR and exit


.SH EXAMPLES

.PP
.nf
.RS
git\-backup
git\-backup \fB-lq\fR
git\-backup \fB-r\fI upstream\fB -c\fI 128\fR
.RE
.fi
.PP


.SH BUGS

If you find issues, please report them:

.UR https://github.com/sarpik/git-backup/issues
https://github.com/sarpik/git-backup/issues
.UE


.SH AUTHOR

Kipras Melnikovas <\fIkipras@kipras.org\fR> :: \fIhttps://kipras.org/\fR :: sarpik \fIhttps://github.com/sarpik/\fR


.SH SEE ALSO

.BR git (1),
.BR git\-remote (1),
.BR git\-stash (1),
.BR git\-branch (1),
.BR git\-push (1)

.I https://github.com/sarpik/git-backup/

