#!/bin/sh

## explanations
#
# config: https://wiki.archlinux.org/index.php/Dotfiles#Tracking_dotfiles_directly_with_Git
#
# git=hub https://github.com/github/hub
#
# config='/usr/bin/hub --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \


alias ka="killall" \
	Q="cd / && $HOME/.scripts/tools/ecryptfs-unmount && i3-msg exit" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c Magit" \
	p="pacman" \
	sp="sudo pacman" \
	SS="sudo systemctl" \
	f="vifm" \
	git="hub" \
	g="git" \
	config="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
	co="config" \
	cs="clear && config add ~/.gitignore && config status" \
	d="docker" \
	r="ranger" \
	k="kanban" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	sv="sudo $EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -lAs" \
	ll="ls -l --all --size --group-directories-first --human-readable --color=auto" \
	lc="ll -C" \
	lsd="lsd --group-dirs first --classify --icon-theme unicode" \
	lcd="lsd --icon-theme fancy" \
	lad="lsd -la --icon-theme fancy" \
	lld="lad" \
	l1d="lsd --classic --icon never -1" \
	quit="exit" \
	q="exit" \
	cls="clear" \
	c="clear" \
	c.="code . && exit" \
	gpgkeys="gpg --list-secret-keys --keyid-format LONG" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	chrome="nohup google-chrome-stable & disown" \
	ce="chrome && exit 0" \
	b="bright" \
	queota="printf \"want some?\n\""

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ;}
se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs  -r $EDITOR ;}
svcp() { vcopy "$(du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf)" ;}
vf() { fzf | xargs -r -I % $EDITOR % ;}

bright() {
	[ -z $1 ] && echo "usage: bright [brightness %]" && return 1
	brightness="$(echo "$1 / 100" | bc -l)"
	echo "brightness $brightness"
	xrandr --output DP-0 --brightness $brightness ;
}
#drm() { docker rm $(docker ps -aq) ;}

# -r removes the last newline! https://stackoverflow.com/a/43830018/9285308
clip() { xclip -r -selection c ;}
copy() { xclip -r -selection c "$1" ;}

md() { pandoc -t markdown $1 | less ;}

# Add file / folder to ~/.gitignore (dotfile management)
gig() {
	if [ -z "$1" ]; then
	#	echo "$(pwd | sed 's|/home/kipras/||g; s|\s|\\ |g;')" >> "$HOME/.gitignore"
		echo "$(pwd | sed 's|'"$HOME"'/||g; s|\s|\\ |g;')" | tee -a "$HOME/.gitignore";
	else
	#	echo "$(pwd | sed 's|/home/kipras/||g; s|\s|\\ |g;'`/$1" >> "$HOME/.gitignore"
	#	echo "$(pwd | sed 's|'"$HOME"'/||g; s|\s|\\ |g;')/$1" >> "$HOME/.gitignore";
 		echo "$(pwd | sed 's|$|/'"$1"'|g; s|'"$HOME"'/||g; s|\s|\\ |g;')" | tee -a "$HOME/.gitignore";
	fi
}

# examples:
# cat file.json | pretty .json
# pretty file.json .json
pretty() {
	if [ -z "$2" ]; then
		prettier --stdin --stdin-filepath $1; # piping
	else
		cat $1 | prettier --stdin --stdin-filepath $2; # using directly
	fi
}

# https://brbsix.github.io/2015/11/23/perform-tab-completion-for-aliases-in-bash/
_completion_loader docker
complete -F _docker d

_completion_loader git
complete -F _git config # config aka dotfile management from $HOME/.dotfiles
complete -F _git co

#_completion_loader sh
#complete -F SS systemctl

#
# gitWrapper
# Originally by Kipras Melnikovas (kipras.org) <kipras@kipras.org>
#
# this is somewhat of a git's 'pre-checkout' hook
# I wish that git implemented it by default
# this one protects from `git checkout -- <foo>` and/or `git checkout -- .`
#
# Credits:
# [1] check if something is an alias: https://stackoverflow.com/a/9783627/9285308
# [2] single quote (') escaping in sed: https://stackoverflow.com/a/18274451
# [3] checking if argv contains a specific command: https://stackoverflow.com/a/47789975/9285308
#

# check if git exists
# TODO improve this checking
$(git --help >/dev/null 2>&1) && gitExists="true" || gitExists="false"
#printf "gitExists $gitExists\n"

if [ "$gitExists" = "true" ]; then
	# Get git's command. Might be aliased
	gitCmd="$(command -v git)"

	# Check if git is aliased [1]
	$(alias git 2>/dev/null >/dev/null) && gitIsAliased="true" || gitIsAliased="false"
	#printf "gitIsAliased $gitIsAliased \n"

	if [ "$gitIsAliased" = "true" ]; then
		# extract the alias [2]. E.g.: alias git='hub' => hub
		trueGit="$(printf "$gitCmd" | sed 's|alias git='\''\(.*\)'\''|\1|g;')"

	elif [ "$gitIsAliased" = "false" ]; then
		# might be /usr/bin/git etc.
		trueGit="$gitCmd"
	fi

	#printf "trueGit = $trueGit\n"

	### ---

	gitWrapper() {
	## Add another case for every `git checkout` alias you have in your .gitconfig

	if [[ " $@ " =~ " checkout -- " ]] || [[ " $@ " =~ " co -- " ]] ; then
		if [[ " $@ " = " checkout -- . " ]] || [[ " $@ " =~ " co -- . " ]]; then
			# VERY dangerous (whole directory)
			printf "==> Detected 'checkout -- .'\n"
			printf " :: This will OVERRIDE **ALL** changes PERMANENTLY!!!"
		else
			# Quite dangerous (will override, but not whole directory)
			printf "==> Detected 'checkout --'\n"
			printf " :: This will OVERRIDE the file(s) PERMANENTLY!"
		fi

		#printf "WARNING\n==> Regex matched this as a 'git checkout -- "

		printf "\n\n==> Are you SURE you want to continue? [y/N]: "

		read choice

		if [ "$choice" = "y" ] || [ "$choice" = "Y" ] || [ "$choice" = "yes" ] || [ "$choice" = "Yes" ]; then
			printf "\n==> I sure hope you know what you are doing...\n"
			"$trueGit" stash -u && \
			printf "\n :: Created a backup stash & probably saved yo butt.\n" && \
			"$trueGit" stash apply >/dev/null 2>&1 && \
			command "$trueGit" "$@"
		else
			printf "==> Aborting\n" && return 1
		fi

	# default case - we did NOT match `checkout --` nor `checkout -- .`
	# put any wrappers / handlers before this.
	else
		# pass the command back to git
		command "$trueGit" "$@"
	fi
	} # end gitWrapper()

	### ---

	### TODO figure out a way to declare a function from a variable

	### EDIT - we should NOT do that.
	### See https://stackoverflow.com/a/48054874/9285308

	### ---

	if [ "$trueGit" = "git" ]; then
		git() {
			gitWrapper "$@"
		}

	elif [ "$trueGit" = "hub" ]; then
		hub() {
			gitWrapper "$@"
		}

	### add any other potential
	### git's commands that could be aliased
	### here

	#	elif [ "$trueGit" = "yetAnotherAlias" ]; then
	#		yetAnotherAlias() {
	#			gitWrapper "$@"
	#		}

	fi # end #trueGit check

fi # end $gitExists check



	###
	#
	# Your git aliases here
	# (if they don't point to the same parent alias)
	#
	###

#	gitWrapperList=( hub )
#
#	for wrapper in gitWrapperList; do
#		"$wrapper"() {
#			command "$wrapper" "$@"
#		}
#	done;

